[package]
name = "synthwave_alpha"
description = "Synthwave inspired color theme."
keywords = ["vscode", "themes", "synthwave"]
repository = "https://github.com/vikpe/synthwave-alpha-vscode"
authors = ["Viktor Persson"]
version = "0.1.0"
edition = "2021"
license = "MIT"
include = ["/Cargo.toml", "/LICENSE", "/README.md", "/src/**", "/tests/**"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
futures = "0.3.30"

[dev-dependencies]
pretty_assertions = "1.4.0"
